name: lightblue Build & Publish CI/CD for main branch
on:
  # Trigger the workflow on push
  # but only for the main branch
  push:
    branches:
      - master
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                java-version: '8'
                distribution: 'adopt'
            - run: mvn --batch-mode --update-snapshots verify
        publish:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v2
              with:
                java-version: '8'
                distribution: 'adopt'
                server-id: ossrh
                server-username: MAVEN_USERNAME
                server-password: MAVEN_PASSWORD
            - name: Publish package
              run: mvn --batch-mode deploy
              env:
                MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
