name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging
      - run: cp core/target/*.jar staging
      - run: cp http/target/*.jar staging
      - run: mkdir staging && cp hystrix/target/*.jar staging
      - run: mkdir staging && cp lightblue-client-integration-test/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
