name: lightblue Build & Publish CI/CD for main branch
on:
  # Trigger the workflow on push, but only for the non-main branches
  push:
    branches:
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
